import type { Metadata } from "next";
import { Nunito, Readex_Pro } from "next/font/google";
import "../globals.css";
import Navbar from "@/layout/Navbar";
import Footer from "@/layout/Footer";

const readexPro = Readex_Pro({
  subsets: ["latin"],
  variable: "--font-readex-pro",
  weight: ["400", "500", "600", "700"],
  style: ["normal"],
  display: "swap",
});

const nunito = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito",
  weight: ["400", "500", "600", "700"],
  style: ["normal"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${readexPro.className} ${nunito.variable} antialiased flex flex-col min-h-screen bg-background_main text-text_primary`}
      >
        <Navbar />
        <main className="flex-1">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
