import { Nunito, Readex_Pro } from "next/font/google";
import "../globals.css";

const readexPro = Readex_Pro({
  subsets: ["latin"],
  variable: "--font-readex-pro",
  weight: ["400", "500", "600", "700"],
  style: ["normal"],
  display: "swap",
});

const nunito = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito",
  weight: ["400", "500", "600", "700"],
  style: ["normal"],
});

export const metadata = {
  title: "Blog Post",
  description: "Generated by create next app",
};

export default function BlogPostLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${readexPro.className} ${nunito.variable} antialiased flex flex-col min-h-screen bg-background_main text-text_primary`}
      >
        {children}
      </body>
    </html>
  );
}
